[package]
name = "mnemonics"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
bip39 = { version = "1.0.0", features = ["rand"] }
bitcoin = "0.32.5"
rand = "0.6"
secp256k1 = "0.24"
fs4 = "0.8"

[[bin]]
name = "mnemonics"
path = "src/main.rs"