[package]
name = "mnemonics"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
bip39 = { version = "2.1.0", features = ["rand"] }
bitcoin = "0.32.5"
rand = "0.9.0"
secp256k1 = "0.30.0"
fs4 = "0.13.1"

[[bin]]
name = "mnemonics"
path = "src/main.rs"